export const ALL_NOTIFICATIONS_DETAILS_REQUEST = "ALL_NOTIFICATIONS_DETAILS_REQUEST";
export const ALL_NOTIFICATIONS_DETAILS_SUCCESS = "ALL_NOTIFICATIONS_DETAILS_SUCCESS";
export const ALL_NOTIFICATIONS_DETAILS_FAILURE = "ALL_NOTIFICATIONS_DETAILS_FAILURE";

export const NOTIFICATION_SUMMARY_REQUEST = "NOTIFICATION_SUMMARY_REQUEST";
export const NOTIFICATION_SUMMARY_SUCCESS = "NOTIFICATION_SUMMARY_SUCCESS";
export const NOTIFICATION_SUMMARY_FAILURE = "NOTIFICATION_SUMMARY_FAILURE";

export const ALL_READ_NOTIFICATIONS_REQUEST = "ALL_READ_NOTIFICATIONS_REQUEST";
export const ALL_READ_NOTIFICATIONS_SUCCESS = "ALL_READ_NOTIFICATIONS_SUCCESS";
export const ALL_READ_NOTIFICATIONS_FAILURE = "ALL_READ_NOTIFICATIONS_FAILURE";

export const ALL_UNREAD_NOTIFICATIONS_REQUEST = "ALL_UNREAD_NOTIFICATIONS_REQUEST";
export const ALL_UNREAD_NOTIFICATIONS_SUCCESS = "ALL_UNREAD_NOTIFICATIONS_SUCCESS";
export const ALL_UNREAD_NOTIFICATIONS_FAILURE = "ALL_UNREAD_NOTIFICATIONS_FAILURE";

export const MARK_ALL_AS_READ_REQUEST = "MARK_ALL_AS_READ_REQUEST";
export const MARK_ALL_AS_READ_SUCCESS = "MARK_ALL_AS_READ_SUCCESS";
export const MARK_ALL_AS_READ_FAILURE = "MARK_ALL_AS_READ_FAILURE";

export const MARK_ALL_AS_UNREAD_REQUEST = "MARK_ALL_AS_UNREAD_REQUEST";
export const MARK_ALL_AS_UNREAD_SUCCESS = "MARK_ALL_AS_UNREAD_SUCCESS";
export const MARK_ALL_AS_UNREAD_FAILURE = "MARK_ALL_AS_UNREAD_FAILURE";

export const MARK_SINGLE_AS_READ_REQUEST = "MARK_SINGLE_AS_READ_REQUEST";
export const MARK_SINGLE_AS_READ_SUCCESS = "MARK_SINGLE_AS_READ_SUCCESS";
export const MARK_SINGLE_AS_READ_FAILURE = "MARK_SINGLE_AS_READ_FAILURE";

export const MARK_SINGLE_AS_UNREAD_REQUEST = "MARK_SINGLE_AS_UNREAD_REQUEST";
export const MARK_SINGLE_AS_UNREAD_SUCCESS = "MARK_SINGLE_AS_UNREAD_SUCCESS";
export const MARK_SINGLE_AS_UNREAD_FAILURE = "MARK_SINGLE_AS_UNREAD_FAILURE";

export const DISABLE_NOTIFICATIONS_REQUEST = "DISABLE_NOTIFICATIONS_REQUEST";
export const DISABLE_NOTIFICATIONS_SUCCESS = "DISABLE_NOTIFICATIONS_SUCCESS";
export const DISABLE_NOTIFICATIONS_FAILURE = "DISABLE_NOTIFICATIONS_FAILURE";

export const ENABLE_NOTIFICATIONS_REQUEST = "ENABLE_NOTIFICATIONS_REQUEST";
export const ENABLE_NOTIFICATIONS_SUCCESS = "ENABLE_NOTIFICATIONS_SUCCESS";
export const ENABLE_NOTIFICATIONS_FAILURE = "ENABLE_NOTIFICATIONS_FAILURE";



