export const GET_ALL_PLANS_REQUEST = "GET_ALL_PLANS_REQUEST";
export const GET_ALL_PLANS_SUCCESS = "GET_ALL_PLANS_SUCCESS";
export const GET_ALL_PLANS_FAILURE = "GET_ALL_PLANS_FAILURE";

export const GET_CURRENT_PLAN_REQUEST = "GET_CURRENT_PLAN_REQUEST";
export const GET_CURRENT_PLAN_SUCCESS = "GET_CURRENT_PLAN_SUCCESS";
export const GET_CURRENT_PLAN_FAILURE = "GET_CURRENT_PLAN_FAILURE";

export const UPGRADE_PLAN_REQUEST = "UPGRADE_PLAN_REQUEST";
export const UPGRADE_PLAN_SUCCESS = "UPGRADE_PLAN_SUCCESS";
export const UPGRADE_PLAN_FAILURE = "UPGRADE_PLAN_FAILURE";

export const RENEW_PLAN_REQUEST = "RENEW_PLAN_REQUEST";
export const RENEW_PLAN_SUCCESS = "RENEW_PLAN_SUCCESS";
export const RENEW_PLAN_FAILURE = "RENEW_PLAN_FAILURE";

export const GET_USER_PAYMENTS_REQUEST = "GET_USER_PAYMENTS_REQUEST";
export const GET_USER_PAYMENTS_SUCCESS = "GET_USER_PAYMENTS_SUCCESS";
export const GET_USER_PAYMENTS_FAILURE = "GET_USER_PAYMENTS_FAILURE";

export const CREATE_PAYMENT_PLAN_REQUEST = "CREATE_PAYMENT_PLAN_REQUEST";
export const CREATE_PAYMENT_PLAN_SUCCESS = "CREATE_PAYMENT_PLAN_SUCCESS";
export const CREATE_PAYMENT_PLAN_FAILURE = "CREATE_PAYMENT_PLAN_FAILURE";

export const GET_ALL_PAYMENTS_REQUEST = "GET_ALL_PAYMENTS_REQUEST";
export const GET_ALL_PAYMENTS_SUCCESS = "GET_ALL_PAYMENTS_SUCCESS";
export const GET_ALL_PAYMENTS_FAILURE = "GET_ALL_PAYMENTS_FAILURE";

export const DELETE_PAYMENT_REQUEST = "DELETE_PAYMENT_REQUEST";
export const DELETE_PAYMENT_SUCCESS = "DELETE_PAYMENT_SUCCESS";
export const DELETE_PAYMENT_FAILURE = "DELETE_PAYMENT_FAILURE";