export const USER_ROLES_REQUEST = "USER_ROLES_REQUEST";
export const USER_ROLES_SUCCESS = "USER_ROLES_SUCCESS";
export const USER_ROLES_FAILURE = "USER_ROLES_FAILURE";

export const LOST_BUT_FOUND_ASSETS_REQUEST = "LOST_BUT_FOUND_ASSETS_REQUEST";
export const LOST_BUT_FOUND_ASSETS_SUCCESS = "LOST_BUT_FOUND_ASSETS_SUCCESS";
export const LOST_BUT_FOUND_ASSETS_FAILURE = "LOST_BUT_FOUND_ASSETS_FAILURE";

export const REPORT_FOUND_ASSETS_REQUEST = "REPORT_FOUND_ASSETS_REQUEST";
export const REPORT_FOUND_ASSETS_SUCCESS = "REPORT_FOUND_ASSETS_SUCCESS";
export const REPORT_FOUND_ASSETS_FAILURE = "REPORT_FOUND_ASSETS_FAILURE";

export const VERIFY_ASSETS_REQUEST = "VERIFY_ASSETS_REQUEST";
export const VERIFY_ASSETS_SUCCESS = "VERIFY_ASSETS_SUCCESS";
export const VERIFY_ASSETS_FAILURE = "VERIFY_ASSETS_FAILURE";

export const ASSET_OWNERSHIP_HISTORY_REQUEST = "ASSET_OWNERSHIP_HISTORY_REQUEST";
export const ASSET_OWNERSHIP_HISTORY_SUCCESS = "ASSET_OWNERSHIP_HISTORY_SUCCESS";
export const ASSET_OWNERSHIP_HISTORY_FAILURE = "ASSET_OWNERSHIP_HISTORY_FAILURE";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const ASSETS_LIST_REQUEST = "ASSETS_LIST_REQUEST";
export const ASSETS_LIST_SUCCESS = "ASSETS_LIST_SUCCESS";
export const ASSETS_LIST_FAILURE = "ASSETS_LIST_FAILURE";

export const MODIFY_ASSET_REQUEST = "MODIFY_ASSET_REQUEST";
export const MODIFY_ASSET_SUCCESS = "MODIFY_ASSET_SUCCESS";
export const MODIFY_ASSET_FAILURE = "MODIFY_ASSET_FAILURE";

export const DELETE_ASSET_REQUEST = "DELETE_ASSET_REQUEST";
export const DELETE_ASSET_SUCCESS = "DELETE_ASSET_SUCCESS";
export const DELETE_ASSET_FAILURE = "DELETE_ASSET_FAILURE";

export const TRANSFER_ASSET_REQUEST = "TRANSFER_ASSET_REQUEST";
export const TRANSFER_ASSET_SUCCESS = "TRANSFER_ASSET_SUCCESS";
export const TRANSFER_ASSET_FAILURE = "TRANSFER_ASSET_FAILURE";

export const BULK_ASSET_TRANSFER_REQUEST = "BULK_ASSET_TRANSFER_REQUEST";
export const BULK_ASSET_TRANSFER_SUCCESS = "BULK_ASSET_TRANSFER_SUCCESS";
export const BULK_ASSET_TRANSFER_FAILURE = "BULK_ASSET_TRANSFER_FAILURE";

export const EDIT_ASSET_TYPE_REQUEST = "EDIT_ASSET_TYPE_REQUEST";
export const EDIT_ASSET_TYPE_SUCCESS = "EDIT_ASSET_TYPE_SUCCESS";
export const EDIT_ASSET_TYPE_FAILURE = "EDIT_ASSET_TYPE_FAILURE";

export const MODAL_ASSET_ID_REQUEST = "MODAL_ASSET_ID_REQUEST";
export const MODAL_ASSET_ID_SUCCESS = "MODAL_ASSET_ID_SUCCESS";
export const MODAL_ASSET_ID_FAILURE = "MODAL_ASSET_ID_FAILURE";

export const SELECTED_ROWS_REQUEST = "SELECTED_ROWS_REQUEST";
export const SELECTED_ROWS_SUCCESS = "SELECTED_ROWS_SUCCESS";
export const SELECTED_ROWS_FAILURE = "SELECTED_ROWS_FAILURE";








