export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const EMAIL_VERIFICATION_START = "EMAIL_VERIFICATION_START";
export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFICATION_SUCCESS";
export const EMAIL_VERIFICATION_FAILURE = "EMAIL_VERIFICATION_FAILURE";

export const FORGOT_PASSWORD_START = "FORGOT_PASSWORD_START";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const RESET_PASSWORD_START = "RESET_PASSWORD_START";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const MODIFY_PROFILE_INFO_START = "MODIFY_PROFILE_INFO_START";
export const MODIFY_PROFILE_INFO_SUCCESS = "MODIFY_PROFILE_INFO_SUCCESS";
export const MODIFY_PROFILE_INFO_FAILURE = "MODIFY_PROFILE_INFO_FAILURE";

export const GET_USER_INFO_START = "GET_USER_INFO_START";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILURE = "GET_USER_INFO_FAILURE";

export const MODIFY_WEBSITE_INFO_START = "MODIFY_WEBSITE_INFO_START";
export const MODIFY_WEBSITE_INFO_SUCCESS = "MODIFY_WEBSITE_INFO_SUCCESS";
export const MODIFY_WEBSITE_INFO_FAILURE = "MODIFY_WEBSITE_INFO_FAILURE";

export const GET_WEBSITE_INFO_START = "GET_WEBSITE_INFO_START";
export const GET_WEBSITE_INFO_SUCCESS = "GET_WEBSITE_INFO_SUCCESS";
export const GET_WEBSITE_INFO_FAILURE = "GET_WEBSITE_INFO_FAILURE";

export const REQUEST_VERIFICATION_LINK_START = "REQUEST_VERIFICATION_LINK_START";
export const REQUEST_VERIFICATION_LINK_SUCCESS = "REQUEST_VERIFICATION_LINK_SUCCESS";
export const REQUEST_VERIFICATION_LINK_FAILURE = "REQUEST_VERIFICATION_LINK_FAILURE";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const GET_ALL_USERS_START = "GET_ALL_USERS_START";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

export const GET_ALL_ADMIN_USERS_START = "GET_ALL_ADMIN_USERS_START";
export const GET_ALL_ADMIN_USERS_SUCCESS = "GET_ALL_ADMIN_USERS_SUCCESS";
export const GET_ALL_ADMIN_USERS_FAILURE = "GET_ALL_ADMIN_USERS_FAILURE";

export const GET_USER_SOCIAL_START = "GET_USER_SOCIAL_START";
export const GET_USER_SOCIAL_SUCCESS = "GET_USER_SOCIAL_SUCCESS";
export const GET_USER_SOCIAL_FAILURE = "GET_USER_SOCIAL_FAILURE";

export const ADD_SOCIAL_ACCOUNT_START = "ADD_SOCIAL_ACCOUNT_START";
export const ADD_SOCIAL_ACCOUNT_SUCCESS = "ADD_SOCIAL_ACCOUNT_SUCCESS";
export const ADD_SOCIAL_ACCOUNT_FAILURE = "ADD_SOCIAL_ACCOUNT_FAILURE";

export const MODIFY_SOCIAL_ACCOUNT_START = "MODIFY_SOCIAL_ACCOUNT_START";
export const MODIFY_SOCIAL_ACCOUNT_SUCCESS = "MODIFY_SOCIAL_ACCOUNT_SUCCESS";
export const MODIFY_SOCIAL_ACCOUNT_FAILURE = "MODIFY_SOCIAL_ACCOUNT_FAILURE";

export const DELETE_SOCIAL_ACCOUNT_START = "DELETE_SOCIAL_ACCOUNT_START";
export const DELETE_SOCIAL_ACCOUNT_SUCCESS = "DELETE_SOCIAL_ACCOUNT_SUCCESS";
export const DELETE_SOCIAL_ACCOUNT_FAILURE = "DELETE_SOCIAL_ACCOUNT_FAILURE";

export const LINK_SOCIAL_ACCOUNT_START = "LINK_SOCIAL_ACCOUNT_START";
export const LINK_SOCIAL_ACCOUNT_SUCCESS = "LINK_SOCIAL_ACCOUNT_SUCCESS";
export const LINK_SOCIAL_ACCOUNT_FAILURE = "LINK_SOCIAL_ACCOUNT_FAILURE";

export const UNLINK_SOCIAL_ACCOUNT_START = "UNLINK_SOCIAL_ACCOUNT_START";
export const UNLINK_SOCIAL_ACCOUNT_SUCCESS = "UNLINK_SOCIAL_ACCOUNT_SUCCESS";
export const UNLINK_SOCIAL_ACCOUNT_FAILURE = "UNLINK_SOCIAL_ACCOUNT_FAILURE";